; AY-3-8912 sound: interrupt setup, a tiny 3-channel pattern player, and
; the sound effects.
;
; The IM2 handler runs once per frame: it advances the tune (channel A =
; bass, B = arpeggio, C = lead; note/keep/release bytes generated by
; tools/music_gen.py from src/music/tune.txt), runs the active sound
; effect (which borrows channel C and the noise generator), and writes
; the 11 shadow registers to the chip. Envelopes are software: a note
; starts at the channel's init volume and decays to its sustain level.

AY_SEL      EQU #FFFD
AY_DATA     EQU #BFFD
MIXER_MUSIC EQU %00111000          ; tone A+B+C on, noise off
MIXER_NOISE EQU %00011100          ; tone A+B on, C off, noise on C

IM2_TABLE   EQU #FE00
IM2_BYTE    EQU #FD
IM2_VEC     EQU #FDFD

; --- interrupt setup -------------------------------------------------------

setup_im2:
    di
    ld hl,IM2_TABLE
    ld a,IM2_BYTE
    ld bc,257
    call mem_fill
    ld a,#C3                       ; JP isr
    ld (IM2_VEC),a
    ld hl,isr
    ld (IM2_VEC+1),hl
    ld a,HIGH IM2_TABLE
    ld i,a
    im 2
    ret

isr:
    push af
    push bc
    push de
    push hl
    push ix
    ld a,(frames)
    inc a
    ld (frames),a
    call music_frame
    call sfx_frame
    call ay_commit
    pop ix
    pop hl
    pop de
    pop bc
    pop af
    ei
    reti

; --- shadow registers ------------------------------------------------------

ay_regs:
    DB 0,0                         ; R0/1  tone A
    DB 0,0                         ; R2/3  tone B
    DB 0,0                         ; R4/5  tone C
    DB 0                           ; R6    noise period
    DB MIXER_MUSIC                 ; R7    mixer
    DB 0,0,0                       ; R8/9/10 volumes

ay_commit:
    ld hl,ay_regs
    xor a
.reg:
    ld bc,AY_SEL
    out (c),a
    ld b,HIGH AY_DATA
    ld d,(hl)
    out (c),d
    inc hl
    inc a
    cp 11
    jr c,.reg
    ret

; silence everything (start-up / after SFX)
ay_mute:
    xor a
    ld (ay_regs+8),a
    ld (ay_regs+9),a
    ld (ay_regs+10),a
    ld a,MIXER_MUSIC
    ld (ay_regs+7),a
    ret

; --- music player ----------------------------------------------------------

; per-channel state block:
;   +0 ptr, +2 song base, +4 volume, +5 sustain, +6 init volume,
;   +7 period reg number, +8 volume reg offset in ay_regs
ch_a:
    DW song_a, song_a
    DB 0, 6, 12, 0, 8
ch_b:
    DW song_b, song_b
    DB 0, 0, 10, 2, 9
ch_c:
    DW song_c, song_c
    DB 0, 5, 13, 4, 10

tempo_cnt:  DB 1

music_init:
    ld hl,song_a
    ld (ch_a),hl
    ld hl,song_b
    ld (ch_b),hl
    ld hl,song_c
    ld (ch_c),hl
    xor a
    ld (ch_a+4),a
    ld (ch_b+4),a
    ld (ch_c+4),a
    ld a,1
    ld (tempo_cnt),a
    ret

music_frame:
    ld a,(music_on)
    or a
    jr nz,.playing
    ; muted: keep A/B silent (C belongs to the SFX when one is active)
    xor a
    ld (ay_regs+8),a
    ld (ay_regs+9),a
    ld a,(sfx_timer)
    or a
    ret nz
    xor a
    ld (ay_regs+10),a
    ret
.playing:
    ld a,(tempo_cnt)
    dec a
    ld (tempo_cnt),a
    jr nz,.envelope
    ld a,music_tempo
    ld (tempo_cnt),a
    ld ix,ch_a
    call ch_row
    ld ix,ch_b
    call ch_row
    ld ix,ch_c
    call ch_row
.envelope:
    ld a,(frames)
    and 1
    jr nz,.vols
    ld ix,ch_a
    call ch_decay
    ld ix,ch_b
    call ch_decay
    ld ix,ch_c
    call ch_decay
.vols:
    ld a,(ch_a+4)
    ld (ay_regs+8),a
    ld a,(ch_b+4)
    ld (ay_regs+9),a
    ld a,(sfx_timer)
    or a
    ret nz                         ; SFX owns channel C and the mixer
    ld a,(ch_c+4)
    ld (ay_regs+10),a
    ld a,MIXER_MUSIC
    ld (ay_regs+7),a
    ret

; advance one song row on channel IX
ch_row:
    ld l,(ix+0)
    ld h,(ix+1)
.read:
    ld a,(hl)
    inc hl
    cp #FF
    jr nz,.have
    ld l,(ix+2)                    ; end marker: loop to the song start
    ld h,(ix+3)
    jr .read
.have:
    ld (ix+0),l
    ld (ix+1),h
    or a
    ret z                          ; 0 = keep ringing
    dec a
    jr nz,.note
    ld (ix+4),0                    ; 1 = release
    ret
.note:
    dec a                          ; note index (stream byte was idx+2)
    add a,a
    ld l,a
    ld h,0
    ld de,ay_note_table
    add hl,de
    ld c,(hl)
    inc hl
    ld b,(hl)                      ; BC = tone period
    ld e,(ix+7)
    ld d,0
    ld hl,ay_regs
    add hl,de
    ld (hl),c
    inc hl
    ld (hl),b
    ld a,(ix+6)
    ld (ix+4),a                    ; volume = init
    ret

; software envelope: decay towards the sustain level
ch_decay:
    ld a,(ix+4)
    cp (ix+5)
    ret z
    ret c
    dec a
    ld (ix+4),a
    ret

; --- sound effects ---------------------------------------------------------
;
; sfx_play(A = effect number) starts one; it owns channel C, the noise
; generator and the mixer until its timer runs out.
;   1 dice click     2 capture (slide up)   3 failed attack (slide down)
;   4 your turn      5 win jingle           6 reinforcement tick

sfx_timer:  DB 0
sfx_type:   DB 0
sfx_period: DW 0
sfx_step:   DW 0
sfx_vol:    DB 0

; table: timer, period, step, volume, mixer - one row per effect
sfx_table:
    DB 3
    DW #0010, 0
    DB 12, MIXER_NOISE             ; 1: click (noise burst)
    DB 24
    DW #01C0, -14
    DB 13, MIXER_MUSIC             ; 2: success slide up
    DB 24
    DW #0090, 12
    DB 13, MIXER_MUSIC             ; 3: fail slide down
    DB 18
    DW #0150, 0
    DB 12, MIXER_MUSIC             ; 4: my-turn beeps
    DB 48
    DW #00D4, 0
    DB 13, MIXER_MUSIC             ; 5: win jingle (arpeggio)
    DB 3
    DW #0068, 0
    DB 10, MIXER_MUSIC             ; 6: supply tick

SFX_ROW EQU 7

sfx_play:
    di                             ; the ISR reads this state
    ld (sfx_type),a
    dec a
    ld e,a
    ld d,0
    ld a,e                         ; row offset = e * SFX_ROW = e*8 - e
    add a,a
    add a,a
    add a,a
    sub e
    ld e,a
    ld hl,sfx_table
    add hl,de
    ld a,(hl)
    ld (sfx_timer),a
    inc hl
    ld a,(hl)
    ld (sfx_period),a
    inc hl
    ld a,(hl)
    ld (sfx_period+1),a
    inc hl
    ld a,(hl)
    ld (sfx_step),a
    inc hl
    ld a,(hl)
    ld (sfx_step+1),a
    inc hl
    ld a,(hl)
    ld (sfx_vol),a
    inc hl
    ld a,(hl)
    ld (ay_regs+7),a
    ld a,4                         ; noise period for the click
    ld (ay_regs+6),a
    ei
    ret

sfx_frame:
    ld a,(sfx_timer)
    or a
    ret z
    dec a
    ld (sfx_timer),a
    jr z,.finish
    ; per-type behaviour
    ld a,(sfx_type)
    cp 4
    jr z,.beeps
    cp 5
    jr z,.jingle
    ; plain: period += step
    ld hl,(sfx_period)
    ld de,(sfx_step)
    add hl,de
    ld (sfx_period),hl
    jr .out
.beeps:
    ; two beeps: silent gap in the middle of the timer range
    ld hl,(sfx_period)
    ld a,(sfx_timer)
    cp 7
    jr c,.out
    cp 12
    jr nc,.out
    ld a,0
    ld (ay_regs+10),a
    ret
.jingle:
    ; C-E-G-C arpeggio: pick the period from how far along we are
    ld a,(sfx_timer)
    rrca
    rrca
    rrca
    and 7                          ; (timer/8): 5..0
    ld e,a
    ld d,0
    ld hl,.jnotes
    add hl,de
    add hl,de
    ld a,(hl)
    inc hl
    ld h,(hl)
    ld l,a
    jr .out
.jnotes:
    DW #006A,#006A,#006A,#008D,#00A8,#00D4  ; timer runs down: C5 E5 G5 C6 C6 C6
.out:
    ld (ay_regs+4),hl
    ld a,(sfx_vol)
    ld (ay_regs+10),a
    ret
.finish:
    ld a,MIXER_MUSIC
    ld (ay_regs+7),a
    xor a
    ld (ay_regs+10),a
    ret
