#!/usr/bin/env python3
"""Compile the text-bitmap font into sjasmplus source.

Usage:
    font_gen.py src/res/font/font8.txt --out build/font8.asm [--force]

Input format (see src/res/font/font8.txt): "char X" where X is a literal
character (ASCII or Cyrillic) or a name (space, dice1..dice8), followed
by 8 rows of 8 columns, '#' = ink pixel, '.' = empty. "alias X Y" makes
character X reuse Y's glyph (for Cyrillic letters shaped like Latin).

Output: an .asm file with two labels:
    font8:    96 glyphs of 8 bytes, game text codes 32..127:
              32..95  = ASCII (undrawn chars are blank),
              96..127 = Cyrillic А..Я (no Ё) - see tools/text_gen.py,
              which encodes UTF-8 strings into these codes.
    dicefont: 8 glyphs, the bold digits 1..8 for dice counts on the map.
"""

import argparse
import sys
from pathlib import Path

NAMED = {"space": " "}
FIRST, LAST = 32, 127
CYR_ORDER = "АБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ"  # codes 96..127


def code_char(code):
    """The character a font code renders (for table comments/lookup)."""
    if code < 96:
        return chr(code)
    return CYR_ORDER[code - 96]


def parse(path):
    glyphs = {}   # key: char or "diceN" -> [8 ints]
    aliases = []  # (new, existing)
    lines = path.read_text().splitlines()
    i = 0
    while i < len(lines):
        line = lines[i].strip()
        i += 1
        if line.startswith("alias "):
            parts = line.split()
            if len(parts) != 3:
                sys.exit(f"error: bad alias line {line!r}")
            aliases.append((parts[1], parts[2]))
            continue
        if not line.startswith("char "):
            continue
        name = line[5:].strip()
        key = NAMED.get(name, name)
        rows = []
        while len(rows) < 8 and i < len(lines):
            row = lines[i].rstrip()
            i += 1
            if not row:
                continue
            if len(row) != 8 or any(c not in ".#" for c in row):
                sys.exit(f"error: glyph {name!r}: bad row {row!r}")
            rows.append(sum(0x80 >> b for b, c in enumerate(row) if c == "#"))
        if len(rows) != 8:
            sys.exit(f"error: glyph {name!r}: expected 8 rows")
        if key in glyphs:
            sys.exit(f"error: glyph {name!r} defined twice")
        glyphs[key] = rows
    for new, src in aliases:
        if src not in glyphs:
            sys.exit(f"error: alias {new!r}: no glyph {src!r}")
        if new in glyphs:
            sys.exit(f"error: alias {new!r} shadows a drawn glyph")
        glyphs[new] = glyphs[src]
    return glyphs


def emit(glyphs):
    out = ["; Generated by tools/font_gen.py from src/res/font/font8.txt",
           "; -- do not edit; edit the .txt and rebuild.", ""]

    out.append("font8:")
    for code in range(FIRST, LAST + 1):
        ch = code_char(code)
        rows = glyphs.get(ch, [0] * 8)
        label = "space" if ch == " " else ch
        out.append("    DB " + ",".join(f"#{r:02X}" for r in rows)
                   + f"  ; {code} '{label}'")

    out.append("")
    out.append("dicefont:")
    for n in range(1, 9):
        key = f"dice{n}"
        if key not in glyphs:
            sys.exit(f"error: missing glyph {key}")
        rows = glyphs[key]
        out.append("    DB " + ",".join(f"#{r:02X}" for r in rows) + f"  ; dice {n}")
    out.append("")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("input", type=Path)
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()

    if args.out.exists() and not args.force:
        sys.exit(f"error: {args.out} exists (use --force)")
    glyphs = parse(args.input)
    drawn = [k for k in glyphs if len(k) == 1]
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(emit(glyphs))
    print(f"{args.out}: {len(drawn)} text glyphs + 8 dice digits")


if __name__ == "__main__":
    main()
