#!/usr/bin/env python3
"""Compile the text-bitmap font into sjasmplus source.

Usage:
    font_gen.py src/res/font/font8.txt --out build/font8.asm [--force]

Input format (see src/res/font/font8.txt): "char X" where X is a literal
character or a name (space, dice1..dice8), followed by 8 rows of 8 columns,
'#' = ink pixel, '.' = empty.

Output: an .asm file with two labels:
    font8:    64 glyphs of 8 bytes, ASCII 32..95 (undrawn chars are blank)
    dicefont: 8 glyphs, the bold digits 1..8 for dice counts on the map.
"""

import argparse
import sys
from pathlib import Path

NAMED = {"space": " "}
FIRST, LAST = 32, 95  # ASCII range covered by font8


def parse(path):
    glyphs = {}   # key: char or "diceN" -> [8 ints]
    lines = path.read_text().splitlines()
    i = 0
    while i < len(lines):
        line = lines[i].strip()
        i += 1
        if not line or line.startswith("#") and not line.startswith("char "):
            continue
        if not line.startswith("char "):
            continue
        name = line[5:].strip()
        key = NAMED.get(name, name)
        rows = []
        while len(rows) < 8 and i < len(lines):
            row = lines[i].rstrip()
            i += 1
            if not row:
                continue
            if len(row) != 8 or any(c not in ".#" for c in row):
                sys.exit(f"error: glyph {name!r}: bad row {row!r}")
            rows.append(sum(0x80 >> b for b, c in enumerate(row) if c == "#"))
        if len(rows) != 8:
            sys.exit(f"error: glyph {name!r}: expected 8 rows")
        if key in glyphs:
            sys.exit(f"error: glyph {name!r} defined twice")
        glyphs[key] = rows
    return glyphs


def emit(glyphs):
    out = ["; Generated by tools/font_gen.py from src/res/font/font8.txt",
           "; -- do not edit; edit the .txt and rebuild.", ""]

    out.append("font8:")
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        rows = glyphs.get(ch, [0] * 8)
        label = "space" if ch == " " else ch
        out.append("    DB " + ",".join(f"#{r:02X}" for r in rows) + f"  ; '{label}'")

    out.append("")
    out.append("dicefont:")
    for n in range(1, 9):
        key = f"dice{n}"
        if key not in glyphs:
            sys.exit(f"error: missing glyph {key}")
        rows = glyphs[key]
        out.append("    DB " + ",".join(f"#{r:02X}" for r in rows) + f"  ; dice {n}")
    out.append("")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("input", type=Path)
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()

    if args.out.exists() and not args.force:
        sys.exit(f"error: {args.out} exists (use --force)")
    glyphs = parse(args.input)
    drawn = [k for k in glyphs if len(k) == 1]
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(emit(glyphs))
    print(f"{args.out}: {len(drawn)} text glyphs + 8 dice digits")


if __name__ == "__main__":
    main()
