#!/usr/bin/env python3
"""Compile the text tracker score into sjasmplus source for the AY player.

Usage:
    music_gen.py src/music/tune.txt --out build/tune.asm [--force]

Input: see src/music/tune.txt for the format (tempo / pattern / order).

Output .asm defines:
    music_tempo   EQU N        frames per row
    ay_note_table:             96 words, AY tone period per note index
    song_a/song_b/song_c:      one byte per row per channel:
                                 0    = keep ringing
                                 1    = release (silence)
                                 2..  = note-on, index into ay_note_table + 2
                                 #FF  = end of song (player loops to start)

Note periods are for the 128K AY clock (1 773 400 Hz): period =
round(clock / 16 / freq), freq = 440 * 2^((idx - 57) / 12) so that
note "A-4" (idx 57) is 440 Hz. Periods are clamped to the AY's 12 bits.
"""

import argparse
import sys
from pathlib import Path

AY_CLOCK = 1_773_400
SEMI = {"C": 0, "C#": 1, "D": 2, "D#": 3, "E": 4, "F": 5,
        "F#": 6, "G": 7, "G#": 8, "A": 9, "A#": 10, "B": 11}
NOTES = 96  # 8 octaves


def note_index(cell):
    # "A-2" / "G#3" -> note table index, or None for --- / off
    if cell == "---" or cell == "off":
        return None
    if len(cell) != 3:
        sys.exit(f"error: bad note {cell!r}")
    name = cell[0] + ("#" if cell[1] == "#" else "")
    if name not in SEMI or not cell[2].isdigit():
        sys.exit(f"error: bad note {cell!r}")
    idx = int(cell[2]) * 12 + SEMI[name]
    if not 0 <= idx < NOTES:
        sys.exit(f"error: note {cell!r} out of range")
    return idx


def cell_byte(cell):
    if cell == "---":
        return 0
    if cell == "off":
        return 1
    return note_index(cell) + 2


def parse(path):
    tempo = 6
    patterns = {}   # name -> [(a, b, c) bytes]
    order = None
    cur = None
    for lineno, raw in enumerate(path.read_text().splitlines(), 1):
        line = raw.split("#", 1)[0].strip() if not raw.strip().startswith("#") else ""
        # careful: '#' also appears in sharps -- only strip full-line comments
        line = "" if raw.strip().startswith("#") else raw.strip()
        if not line:
            continue
        words = line.split()
        if words[0] == "tempo":
            tempo = int(words[1])
        elif words[0] == "pattern":
            cur = words[1]
            patterns[cur] = []
        elif words[0] == "order":
            order = words[1:]
        else:
            if cur is None:
                sys.exit(f"error: line {lineno}: row outside a pattern")
            if len(words) != 3:
                sys.exit(f"error: line {lineno}: expected 3 cells, got {words}")
            patterns[cur].append(tuple(cell_byte(w) for w in words))
    if not order:
        sys.exit("error: no order line")
    for name in order:
        if name not in patterns:
            sys.exit(f"error: order references unknown pattern {name!r}")
    return tempo, patterns, order


def period(idx):
    freq = 440.0 * 2.0 ** ((idx - 57) / 12.0)
    return min(4095, round(AY_CLOCK / 16.0 / freq))


def emit(tempo, patterns, order):
    rows = []
    for name in order:
        rows.extend(patterns[name])
    out = ["; Generated by tools/music_gen.py from src/music/tune.txt",
           "; -- do not edit; edit the .txt and rebuild.", "",
           f"music_tempo EQU {tempo}", "",
           "ay_note_table:"]
    for base in range(0, NOTES, 12):
        words = ",".join(f"#{period(i):03X}" for i in range(base, base + 12))
        out.append(f"    DW {words}  ; octave {base // 12}")
    for ch, label in ((0, "song_a"), (1, "song_b"), (2, "song_c")):
        out.append("")
        out.append(f"{label}:")
        for base in range(0, len(rows), 16):
            chunk = rows[base:base + 16]
            out.append("    DB " + ",".join(f"#{r[ch]:02X}" for r in chunk))
        out.append("    DB #FF")
    out.append("")
    return "\n".join(out), len(rows)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("input", type=Path)
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()
    if args.out.exists() and not args.force:
        sys.exit(f"error: {args.out} exists (use --force)")
    tempo, patterns, order = parse(args.input)
    text, nrows = emit(tempo, patterns, order)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text)
    print(f"{args.out}: {len(patterns)} patterns, {nrows} rows, tempo {tempo}")


if __name__ == "__main__":
    main()
